### ISSUE TITLE
How to decrypt other people's passwords ?

### ISSUE THREAD

**Issue by ghost** [mauricelambert/ChromePasswordsStealer#2]
How do I get other people's passwords by sending them the executable? Can you please explain step by step?

**Comment by mauricelambert** [comment]
You can only get your passwords for now. I will implement the feature to get other people's passwords.

**Comment by mauricelambert** [comment]
Is not possible to get other user's passwords because i need to use `CryptUnprotectData` to get key. This function use environment variables of current user so we can't use it from another user ([microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptunprotectdata), [stackoverflow explanation](https://stackoverflow.com/questions/23201146/how-to-decrypt-data-which-is-crypted-by-cryptprotectdata-function)).

**Comment by mauricelambert** [comment]
Understanding microsoft `dpapi` and how to decrypt other people's passwords:
 - https://www.synacktiv.com/ressources/univershell_2017_dpapi.pdf
 - https://www.hackthebox.com/blog/seized-ca-ctf-2022-forensics-writeup
